name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, and thanks for creating your first issue on the bacon-chainsaw repository."
        pr-message: "Hello, and thanks for creating your first pull request on the bacon-chainsaw repository"
